# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
    - linux
    - osx

# More informative failures:
after_failure:
    - cat "${RCHECK_DIR}/00install.out"

